"use client";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Activity, ArrowRight, ArrowUpRight, Check, Copy, CreditCard, Fingerprint, KeyRound, Link2, LoaderCircle, LogOut, Plus, ShieldCheck, SlidersHorizontal, Terminal, Wallet } from "lucide-react";
import { money } from "@/lib/contracts";
import { cn } from "@/lib/utils";
import type { PublicAccount, PurchaseIntent } from "@/lib/platform-types";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, CardAction } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { ConnectPhone } from "./connect-phone";
import SubscriptionPlans from "./subscription-plans";
import { Landing, Brand } from "./landing";
import { ThemeToggle } from "./theme-toggle";

function Message({ children, error = false }: { children: ReactNode; error?: boolean }) {
  return <Alert variant={error ? "destructive" : "default"} role={error ? "alert" : "status"}><AlertDescription>{children}</AlertDescription></Alert>;
}
function EmptyState({ title, detail, children }: { title: string; detail: string; children?: ReactNode }) {
  return <Card className="items-center py-12 text-center"><Fingerprint className="size-8 text-muted-foreground" /><CardHeader><CardTitle>{title}</CardTitle><CardDescription className="max-w-md">{detail}</CardDescription></CardHeader>{children && <CardContent>{children}</CardContent>}</Card>;
}
function WorkspaceNavigation({ account, tab, setTab, logout }: { account: PublicAccount; tab: string; setTab: (tab: string) => void; logout: () => void }) {
  const { setOpenMobile } = useSidebar();
  return <Sidebar collapsible="icon">
    <SidebarHeader className="gap-5 p-4 group-data-[collapsible=icon]:p-2"><div className="group-data-[collapsible=icon]:hidden"><Brand /></div><img src="/logo.png" alt="AgentPass" className="hidden size-8 dark:invert group-data-[collapsible=icon]:block" /><div className="flex items-center gap-3 rounded-lg border p-3 group-data-[collapsible=icon]:hidden"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-muted font-medium">{account.name.slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-medium">{account.name}</p><p className="text-xs text-muted-foreground">Personal workspace</p></div></div></SidebarHeader>
    <SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu>{tabs.map(({name,icon: Icon})=><SidebarMenuItem key={name}><SidebarMenuButton tooltip={name} isActive={tab===name} onClick={()=>{setTab(name);setOpenMobile(false);}}><Icon /><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}<SidebarMenuItem><ConnectPhone /></SidebarMenuItem></SidebarMenu></SidebarGroup></SidebarContent>
    <SidebarFooter className="p-3"><div className="mb-3 rounded-lg border p-3 text-xs leading-5 text-muted-foreground group-data-[collapsible=icon]:hidden"><ShieldCheck className="mb-2 size-4 text-sidebar-primary" /><p className="mb-1 font-medium text-foreground">Authority stays with you.</p>Only you can change policies or bind payment accounts.</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton tooltip="Sign out" onClick={logout}><LogOut /><span>Sign out</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter>
  </Sidebar>;
}

async function api(path: string, input?: unknown) {
  const r = await fetch(`/api/platform/${path}`, { method: input === undefined ? "GET" : "POST", headers: { "Content-Type": "application/json" }, ...(input === undefined ? {} : { body: JSON.stringify(input) }) });
  const result = await r.json();
  if (!r.ok) throw new Error(result.error || "Request failed.");
  return result;
}
const tabs = [{ name: "Agents", icon: Fingerprint }, { name: "Payment accounts", icon: Wallet }, { name: "Activity", icon: Activity }, { name: "Connect plugin", icon: Terminal }, { name: "Subscription", icon: CreditCard }];
export default function AgentPass() {
  const [account, setAccount] = useState<PublicAccount | null>(null);
  const [loading, setLoading] = useState(true), [signup, setSignup] = useState(false), [authOpen, setAuthOpen] = useState(false);
  const [tab, setTab] = useState("Agents"), [selected, setSelected] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [modal, setModal] = useState<"agent" | "wallet" | "token" | "intent" | null>(null);
  const [token, setToken] = useState(""), [walletKind, setWalletKind] = useState("upi");
  const [intent, setIntent] = useState<PurchaseIntent | null>(null), [verification, setVerification] = useState("");
  const [avatars, setAvatars] = useState<string[]>([]);
  const refresh = useCallback(async () => { const result = await api("account"); setAccount(result.account); }, []);
  useEffect(() => { void refresh().catch(() => {}).finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => { void api("avatars").then(r => setAvatars(r.avatars || [])).catch(() => {}); }, []);
  useEffect(() => { if (!account) return; const timer = setInterval(() => void refresh().catch(() => {}), 5000); return () => clearInterval(timer); }, [!!account, refresh]);
  const agent = account?.agents.find(a => a.id === selected) || account?.agents[0];
  async function action(fn: () => Promise<void>) {
    if (busy) return;
    setBusy(true); setError(""); setNotice("");
    try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  function close() { setModal(null); setToken(""); }
  async function signIn(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget);
    await action(async () => { const result = await api(signup ? "signup" : "login", { email: data.get("email"), password: data.get("password"), ...(signup ? { name: data.get("name") } : {}) }); setAccount(result.account); setAuthOpen(false); });
  }
  async function formAction(e: FormEvent<HTMLFormElement>, path: string, transform?: (values: FormData) => unknown) {
    e.preventDefault(); const values = new FormData(e.currentTarget);
    await action(async () => {
      const result = await api(path, transform ? transform(values) : Object.fromEntries(values));
      if (result.token) { setToken(result.token); setModal("token"); if (result.agent) setSelected(result.agent.id); }
      else setModal(null);
      await refresh(); setNotice("Saved.");
    });
  }
  const authForm = <form onSubmit={signIn}>
    <FieldGroup>
      {signup && <Field><FieldLabel htmlFor="auth-name">Your name</FieldLabel><Input id="auth-name" name="name" autoComplete="name" maxLength={80} required /></Field>}
      <Field><FieldLabel htmlFor="auth-email">Email</FieldLabel><Input id="auth-email" name="email" type="email" autoComplete="email" maxLength={200} required /></Field>
      <Field><FieldLabel htmlFor="auth-password">Password</FieldLabel><Input id="auth-password" name="password" type="password" autoComplete={signup ? "new-password" : "current-password"} minLength={12} maxLength={200} required aria-describedby="password-help" /><FieldDescription id="password-help" className="text-xs">At least 12 characters. Email verification and password recovery are not available in this event build.</FieldDescription></Field>
      <Button type="submit" disabled={busy}>{busy && <LoaderCircle className="animate-spin" />}{signup ? "Create trial account" : "Sign in"}</Button>
      <Button variant="ghost" className="h-auto whitespace-normal" onClick={() => { setSignup(!signup); setError(""); }}>{signup ? "Already have an account? Sign in" : "New to AgentPass? Create an account"}</Button>
    </FieldGroup>
  </form>;
  if (loading) return <main className="grid min-h-svh place-content-center justify-items-center gap-4 bg-background text-muted-foreground"><LoaderCircle className="size-7 animate-spin" /><p className="text-sm">Opening AgentPass…</p></main>;
  return <>
    {!account ? <Landing onStart={() => { setSignup(true); setAuthOpen(true); }} onSignIn={() => { setSignup(false); setAuthOpen(true); }} /> : <SidebarProvider>
      <WorkspaceNavigation account={account} tab={tab} setTab={setTab} logout={() => action(async () => { await api("logout", {}); setAccount(null); setToken(""); })} />
      <SidebarInset className="min-w-0">
        <header className="flex h-16 shrink-0 items-center justify-between gap-4 border-b px-4 md:px-7"><div className="flex items-center gap-3"><SidebarTrigger /><Separator orientation="vertical" className="!h-4" /><span className="hidden text-sm text-muted-foreground sm:block">Your workspace</span><span className="text-sm font-medium">{tab}</span></div><div className="flex items-center gap-2"><Badge variant="outline" className="hidden sm:inline-flex">Event trial · no charge</Badge><ThemeToggle /></div></header>
        <div className="mx-auto w-full max-w-[1500px] space-y-6 p-4 md:p-7 lg:p-8">
          {tab !== "Subscription" && <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{tab === "Agents" ? "Your agents" : tab}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{tab === "Agents" ? "Manage their identities, payment accounts, and spending authority." : tab === "Payment accounts" ? "Bind existing accounts without sharing financial secrets with your agents." : tab === "Activity" ? "Purchase permissions, reported orders, and the evidence behind them." : "Connect Hermes or another MCP-compatible agent."}</p></div>{tab === "Agents" && <Button onClick={() => setModal("agent")}><Plus />Register agent</Button>}{tab === "Payment accounts" && <Button onClick={() => setModal("wallet")}><Plus />Add account reference</Button>}</div>}
          {error && <Message error>{error}</Message>}{notice && <Message>{notice}</Message>}
          {tab === "Agents" && <>
            <div className="grid gap-4 sm:grid-cols-3">{[{ label: "Active agents", value: account.agents.filter(a => a.status === "active").length, icon: Fingerprint, note: "Identities with spending authority" }, { label: "Account references", value: account.wallets.length, icon: Wallet, note: "UPI and card references" }, { label: "Purchase requests", value: account.intents.length, icon: Activity, note: "Recorded in this workspace" }].map(({ label, value, icon: Icon, note }) => <Card key={label}><CardHeader><CardDescription>{label}</CardDescription><CardAction><Icon className="size-4 text-muted-foreground" /></CardAction><CardTitle className="text-3xl tabular-nums">{value}</CardTitle></CardHeader><CardFooter className="text-xs text-muted-foreground">{note}</CardFooter></Card>)}</div>
            {!account.agents.length ? <EmptyState title="Meet your first agent" detail="Register Hermes, give it an identity, and choose the rules that follow it."><Button onClick={() => setModal("agent")}>Register your first agent <ArrowRight /></Button></EmptyState> : <>
              <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{account.agents.map(a => <button key={a.id} type="button" aria-pressed={agent?.id === a.id} aria-label={`Select ${a.name}`} onClick={() => setSelected(a.id)} className="rounded-xl text-left outline-none focus-visible:ring-2 focus-visible:ring-ring"><Card className={cn("h-full transition-shadow hover:ring-ring/70", agent?.id === a.id && "ring-2 ring-sidebar-primary/70")}><CardHeader><div className="mb-2 flex items-center justify-between"><img src={`/${a.avatar}`} alt="" className="size-11 rounded-xl bg-muted object-cover" /><Badge variant={a.status === "active" ? "secondary" : "destructive"}>{a.status === "active" && <span className="size-1.5 rounded-full bg-chart-2" />}{a.status === "active" ? "Active" : "Revoked"}</Badge></div><CardTitle>{a.name}</CardTitle><CardDescription>{a.runtime} · Owner attested</CardDescription></CardHeader><CardContent className="font-mono text-xs text-muted-foreground">{a.id.slice(0,18)}…</CardContent><CardFooter className="justify-between text-xs"><span>{money(a.budget-a.spent-a.reserved)} allowance left</span><ArrowUpRight className="size-4 text-muted-foreground" /></CardFooter></Card></button>)}</div>
              {agent && <div className="grid items-start gap-6 xl:grid-cols-2">
                <Card><CardHeader><CardTitle>{agent.name}’s spending policy</CardTitle><CardDescription>Limits are permissions, not a funded balance.</CardDescription><CardAction><SlidersHorizontal className="size-4 text-muted-foreground" /></CardAction></CardHeader><CardContent>
                  <form key={agent.id+":"+agent.policyVersion} onSubmit={e=>formAction(e,`agents/${agent.id}/policy`,f=>({budget:Math.round(Number(f.get("budget"))*100),perPurchase:Math.round(Number(f.get("cap"))*100),allowedMerchants:String(f.get("merchants")).split(/[,\n]/).map(s=>s.trim()).filter(Boolean)}))}><FieldGroup>
                    <div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="budget">Total allowance (₹)</FieldLabel><Input id="budget" name="budget" type="number" min="1" max="100000" step="0.01" defaultValue={agent.budget/100} required /></Field><Field><FieldLabel htmlFor="cap">Per purchase (₹)</FieldLabel><Input id="cap" name="cap" type="number" min="1" max="100000" step="0.01" defaultValue={agent.perPurchase/100} required /></Field></div>
                    <Field><FieldLabel htmlFor="merchants">Allowed merchant domains</FieldLabel><Input id="merchants" name="merchants" defaultValue={agent.allowedMerchants.join(", ")} placeholder="amazon.in, flipkart.com" required aria-describedby="merchant-help" /><FieldDescription id="merchant-help" className="text-xs">Comma-separated domains. Subdomains are included.</FieldDescription></Field>
                    <div className="grid grid-cols-2 gap-3">{[["Reported spend",agent.spent],["Reserved",agent.reserved]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-medium tabular-nums">{money(Number(value))}</p></div>)}</div>
                    <Button type="submit" disabled={busy}>Save policy <Check /></Button>
                  </FieldGroup></form>
                </CardContent><CardFooter className="text-xs leading-5 text-muted-foreground">New requests are checked against these limits and merchants.</CardFooter></Card>
                <Card><CardHeader><CardTitle>Identity & account binding</CardTitle><CardDescription>Switch accounts without resetting history.</CardDescription><CardAction><Link2 className="size-4 text-muted-foreground" /></CardAction></CardHeader><CardContent className="space-y-5">
                  <dl className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-4 gap-y-3 text-xs"><dt className="text-muted-foreground">Stable identity</dt><dd className="break-all font-mono">{agent.id}</dd><dt className="text-muted-foreground">Binding version</dt><dd>v{agent.bindingVersion}</dd><dt className="text-muted-foreground">Owner</dt><dd>{account.name}</dd><dt className="text-muted-foreground">Last plugin contact</dt><dd>{agent.lastSeen?new Date(agent.lastSeen).toLocaleString():"Not connected"}</dd></dl>
                  <Separator /><form key={agent.id+":"+agent.bindingVersion} onSubmit={e=>formAction(e,`agents/${agent.id}/binding`)}><FieldGroup><Field><FieldLabel htmlFor="wallet-binding">Payment account</FieldLabel><NativeSelect id="wallet-binding" className="w-full" name="walletId" defaultValue={agent.walletId||""} required><NativeSelectOption value="" disabled>Select an account reference</NativeSelectOption>{account.wallets.map(w=><NativeSelectOption key={w.id} value={w.id}>{w.label} · {w.maskedReference}</NativeSelectOption>)}</NativeSelect></Field><Button type="submit" variant="outline" disabled={busy||!account.wallets.length}>Save binding</Button></FieldGroup></form>
                  {!account.wallets.length && <Button variant="link" className="h-auto whitespace-normal px-0" onClick={()=>{setTab("Payment accounts");setModal("wallet");}}>Add your first account reference <ArrowRight /></Button>}
                  <p className="text-xs leading-5 text-muted-foreground">Payment execution is not connected. References identify the selected account; they do not grant access to funds.</p>
                </CardContent><CardFooter><Button className="w-full" variant={agent.status==="active"?"destructive":"outline"} disabled={busy} onClick={()=>action(async()=>{await api(`agents/${agent.id}/${agent.status==="active"?"revoke":"resume"}`,{});await refresh();})}>{agent.status==="active"?"Revoke spending authority":"Restore spending authority"}</Button></CardFooter></Card>
              </div>}
            </>}
          </>}
          {tab === "Payment accounts" && <>
            <Alert><ShieldCheck /><AlertDescription>These are owner-declared, masked references. AgentPass does not hold money, verify bank balances, or enable automatic debits through these references.</AlertDescription></Alert>
            {!account.wallets.length ? <EmptyState title="No payment accounts yet" detail="Add a UPI or card reference, then bind it to an agent."><Button onClick={()=>setModal("wallet")}>Add account reference</Button></EmptyState> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{account.wallets.map(w=><Card key={w.id}><CardHeader><div className="mb-3 flex items-center justify-between"><Wallet className="size-5" /><Badge variant="outline">Reference only</Badge></div><CardTitle>{w.label}</CardTitle><CardDescription>{w.kind.toUpperCase()} · {w.maskedReference}</CardDescription></CardHeader><CardFooter className="flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{account.agents.filter(a=>a.walletId===w.id).length} agents bound</span><span>No execution adapter</span></CardFooter></Card>)}</div>}
          </>}
          {tab === "Activity" && <div className="grid items-start gap-6 xl:grid-cols-[1.3fr_1fr]"><Card className="min-w-0"><CardHeader><CardTitle>Purchase intents</CardTitle><CardDescription>Authorizations are not payment confirmations.</CardDescription></CardHeader><CardContent>{!account.intents.length?<p className="py-8 text-center text-sm text-muted-foreground">No requests yet. Connect your plugin to get started.</p>:<Table><TableHeader><TableRow><TableHead>Purchase / merchant</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{account.intents.map(i=><TableRow key={i.id}><TableCell className="min-w-44 max-w-64 whitespace-normal"><p className="font-medium">{i.item}</p><p className="mt-1 text-xs text-muted-foreground">{i.merchant}</p></TableCell><TableCell className="tabular-nums">{money(i.amount)}</TableCell><TableCell><Badge variant={i.status==="blocked"?"destructive":"outline"}>{i.status==="reported"?"Order reported":i.status}</Badge></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Inspect ${i.item}`} onClick={()=>{setIntent(i);setVerification("");setModal("intent");}}><ArrowUpRight /></Button></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card><Card><CardHeader><CardTitle>Audit trail</CardTitle><CardAction><Badge variant="outline">Refreshes every 5s</Badge></CardAction></CardHeader><CardContent className="max-h-[600px] space-y-5 overflow-auto">{account.events.slice(0,30).map(e=><div key={e.id} className="flex gap-3"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-muted"><Activity className="size-4 text-muted-foreground" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-1 text-xs"><span className="font-medium capitalize">{e.type}</span><time className="text-muted-foreground">{new Date(e.time).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div><p className="mt-1 text-sm leading-6 break-words text-muted-foreground">{e.detail}</p></div></div>)}</CardContent></Card></div>}
          {tab === "Connect plugin" && <Card className="max-w-3xl"><CardHeader><CardTitle>Give your agent its passport</CardTitle><CardDescription>One credential per agent. Owner controls stay outside the runtime.</CardDescription><CardAction><Terminal className="size-5 text-muted-foreground" /></CardAction></CardHeader><CardContent className="space-y-6"><ol className="ml-5 list-decimal space-y-5 text-sm marker:text-muted-foreground"><li className="pl-2"><p className="font-medium">Register an agent and bind its account</p><p className="mt-1 leading-6 text-muted-foreground">Configure the merchant allowlist and spending limits under Agents.</p></li><li className="pl-2"><p className="font-medium">Get a scoped plugin credential</p><p className="mt-1 leading-6 text-muted-foreground">Credentials are shown once at registration. Rotation invalidates the previous credential.</p></li><li className="pl-2"><p className="font-medium">Connect Hermes or another MCP client</p><code className="my-2 block rounded-lg border bg-muted p-3 text-xs">npm run plugin:configure</code><p className="leading-6 text-muted-foreground">Run from this repository. Paste the credential into the local prompt, then run <code className="text-foreground">npm run hermes:platform</code>.</p></li><li className="pl-2"><p className="font-medium">Use your agent’s shopping tools</p><blockquote className="mt-2 rounded-lg border bg-muted/50 p-3 leading-6 text-muted-foreground">Find an umbrella on Amazon India under ₹800. Use AgentPass to check my identity and authorize the exact item and final total. Only report payment when the merchant confirms it.</blockquote><p className="mt-2 text-xs leading-5 text-muted-foreground">The plugin supplies identity and authority tools. Your agent runtime supplies browsing and shopping.</p></li></ol>{agent&&<div className="space-y-3 border-t pt-5"><Field><FieldLabel htmlFor="plugin-agent">Agent</FieldLabel><NativeSelect id="plugin-agent" className="w-full" value={agent.id} onChange={e=>setSelected(e.target.value)}>{account.agents.map(a=><NativeSelectOption key={a.id} value={a.id}>{a.name}</NativeSelectOption>)}</NativeSelect></Field><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{const r=await api(`agents/${agent.id}/token`,{});setToken(r.token);setModal("token");await refresh();})}><KeyRound />Rotate & show new credential</Button></div>}</CardContent><CardFooter className="text-xs leading-5 text-muted-foreground">Tools include identity, purchase authorization, history, verification, order reporting, and phone payment handoff. Agents cannot edit owner policies.</CardFooter></Card>}
          {tab === "Subscription" && <SubscriptionPlans agentCount={account.agents.length} walletCount={account.wallets.length} intentCount={account.intents.length} onConnect={()=>setTab("Connect plugin")} />}
        </div>
      </SidebarInset>
    </SidebarProvider>}
    <Dialog open={authOpen || !!modal} onOpenChange={open=>{if(!open){close();setAuthOpen(false);}}}>
      <DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-md">
        <DialogHeader><DialogTitle>{authOpen ? signup ? "Your agents start here" : "Welcome back" : modal==="agent"?"Register an agent":modal==="wallet"?"Add an account reference":modal==="token"?"Your agent credential":intent?.item||"Purchase details"}</DialogTitle><DialogDescription>{authOpen?signup?"Create your AgentPass event-trial workspace.":"Sign in to manage your identities and spending rules.":modal==="agent"?"Create a stable identity and a scoped plugin credential.":modal==="wallet"?"We store a masked reference. This does not connect a bank or enable automatic payment.":modal==="token"?"Shown once. Store it in your local plugin configuration, not in prompts.":intent?.reason}</DialogDescription></DialogHeader>
        {authOpen && authForm}
        {modal==="agent"&&<form onSubmit={e=>formAction(e,"agents")}><FieldGroup><Field><FieldLabel htmlFor="agent-name">Agent name</FieldLabel><Input id="agent-name" name="name" placeholder="Atlas" maxLength={60} required /></Field><Field><FieldLabel htmlFor="agent-runtime">Runtime</FieldLabel><Input id="agent-runtime" name="runtime" defaultValue="Hermes" maxLength={60} required /></Field><fieldset><legend className="mb-3 text-sm font-medium">Choose a sprite</legend><div className="flex flex-wrap gap-3">{avatars.map(file=>{const taken=account?.agents.some(x=>x.status==="active"&&x.avatar===file);return <label key={file} className={cn("relative cursor-pointer rounded-xl border-2 border-transparent bg-muted p-1 has-[:checked]:border-sidebar-primary has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-ring",taken&&"cursor-not-allowed opacity-30")} title={taken?`${file} is already in use`:file}><input type="radio" name="avatar" value={file} required disabled={taken} className="sr-only" aria-label={file} /><img src={`/${file}`} alt="" className="size-11 rounded-lg object-cover" /></label>;})}</div></fieldset><Button type="submit" disabled={busy||!avatars.length}>Register agent</Button></FieldGroup></form>}
        {modal==="wallet"&&<form onSubmit={e=>formAction(e,"wallets")}><FieldGroup><Field><FieldLabel htmlFor="account-label">Account label</FieldLabel><Input id="account-label" name="label" placeholder="Personal UPI" maxLength={60} required /></Field><Field><FieldLabel htmlFor="account-kind">Account type</FieldLabel><NativeSelect id="account-kind" className="w-full" name="kind" value={walletKind} onChange={e=>setWalletKind(e.target.value)}><NativeSelectOption value="upi">UPI</NativeSelectOption><NativeSelectOption value="card">Card</NativeSelectOption></NativeSelect></Field><Field><FieldLabel htmlFor="account-reference">{walletKind==="upi"?"UPI ID":"Last four card digits only"}</FieldLabel><Input id="account-reference" key={walletKind} name="reference" placeholder={walletKind==="upi"?"name@bank":"1234"} maxLength={walletKind==="upi"?100:4} pattern={walletKind==="card"?"[0-9]{4}":undefined} required autoComplete="off" aria-describedby="reference-help" /><FieldDescription id="reference-help" className="text-xs">Never enter a UPI PIN, complete card number, CVV or OTP.</FieldDescription></Field><Button type="submit" disabled={busy}>Save masked reference</Button></FieldGroup></form>}
        {modal==="token"&&<><Textarea className="min-h-28 break-all font-mono text-xs" aria-label="Agent credential" readOnly value={token} /><Button onClick={()=>action(async()=>{await navigator.clipboard.writeText(token);setNotice("Credential copied. Paste it into the local plugin setup prompt.");})}><Copy />Copy credential</Button><p className="text-xs leading-5 text-muted-foreground">Access is restricted to this account and agent. Rotate the credential to invalidate it.</p></>}
        {modal==="intent"&&intent&&<><dl className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-4 gap-y-3 text-sm">{[["Merchant",intent.merchant],["Total",money(intent.amount)],["Status",intent.status],["Payment evidence",intent.evidenceSource||"No payment confirmed"],["Authorization expiry",new Date(intent.expiresAt).toLocaleString()],["Request ID",intent.requestId]].map(([label,value])=><div key={label} className="contents"><dt className="text-muted-foreground">{label}</dt><dd className="break-all">{value}</dd></div>)}</dl>{intent.proof&&<Button disabled={busy} onClick={()=>action(async()=>{const r=await api("verify",{payload:intent.proof!.payload,signature:intent.proof!.signature});setVerification(`${r.authorized?"Current authority valid":"Not currently authorized"}. ${r.reason}`);})}><ShieldCheck />Verify current authority</Button>}{verification&&<Message>{verification}</Message>}{intent.status==="authorized"&&<Button variant="outline" className="h-auto whitespace-normal py-2" disabled={busy} onClick={()=>action(async()=>{await api("cancel",{intentId:intent.id,confirmNoPayment:true});setModal(null);await refresh();})}>Confirm no payment occurred & release reservation</Button>}<p className="text-xs leading-5 text-muted-foreground">Releasing a reservation does not cancel an order or payment at the merchant.</p></>}
        {error&&<Message error>{error}</Message>}{notice&&<p role="status" className="text-xs text-muted-foreground">{notice}</p>}
      </DialogContent>
    </Dialog>
  </>;
}
