"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Activity, ArrowRight, ArrowUpRight, Check, Copy, CreditCard, Fingerprint, KeyRound, Link2, LoaderCircle, LogOut, Plus, ShieldCheck, SlidersHorizontal, Terminal, Wallet, X } from "lucide-react";
import { money } from "@/lib/contracts";
import type { PublicAccount, PurchaseIntent } from "@/lib/platform-types";

async function api(path: string, input?: unknown) {
  const r = await fetch(`/api/platform/${path}`, { method: input === undefined ? "GET" : "POST", headers: { "Content-Type": "application/json" }, ...(input === undefined ? {} : { body: JSON.stringify(input) }) });
  const result = await r.json();
  if (!r.ok) throw new Error(result.error || "Request failed.");
  return result;
}
const tabs = [{ name: "Agents", icon: Fingerprint }, { name: "Payment accounts", icon: Wallet }, { name: "Activity", icon: Activity }, { name: "Connect plugin", icon: Terminal }, { name: "Subscription", icon: CreditCard }];
export default function AgentPass() {
  const [account, setAccount] = useState<PublicAccount | null>(null);
  const [loading, setLoading] = useState(true), [signup, setSignup] = useState(false), [authOpen, setAuthOpen] = useState(false);
  const [tab, setTab] = useState("Agents"), [selected, setSelected] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [modal, setModal] = useState<"agent" | "wallet" | "token" | "intent" | null>(null);
  const [token, setToken] = useState(""), [walletKind, setWalletKind] = useState("upi");
  const [intent, setIntent] = useState<PurchaseIntent | null>(null), [verification, setVerification] = useState("");
  const refresh = useCallback(async () => { const result = await api("account"); setAccount(result.account); }, []);
  useEffect(() => { void refresh().catch(() => {}).finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => { if (!account) return; const timer = setInterval(() => void refresh().catch(() => {}), 5000); return () => clearInterval(timer); }, [!!account, refresh]);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === "Escape") { setModal(null); setToken(""); setAuthOpen(false); } }; document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, []);
  const agent = account?.agents.find(a => a.id === selected) || account?.agents[0];
  async function action(fn: () => Promise<void>) {
    if (busy) return;
    setBusy(true); setError(""); setNotice("");
    try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  function close() { setModal(null); setToken(""); }
  async function signIn(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget);
    await action(async () => { const result = await api(signup ? "signup" : "login", { email: data.get("email"), password: data.get("password"), ...(signup ? { name: data.get("name") } : {}) }); setAccount(result.account); setAuthOpen(false); });
  }
  async function formAction(e: FormEvent<HTMLFormElement>, path: string, transform?: (values: FormData) => unknown) {
    e.preventDefault(); const values = new FormData(e.currentTarget);
    await action(async () => {
      const result = await api(path, transform ? transform(values) : Object.fromEntries(values));
      if (result.token) { setToken(result.token); setModal("token"); if (result.agent) setSelected(result.agent.id); }
      else setModal(null);
      await refresh(); setNotice("Saved.");
    });
  }
  const authForm = <form onSubmit={signIn} className="saas-form">{signup && <label>Your name<input name="name" autoComplete="name" maxLength={80} required /></label>}<label>Email<input name="email" type="email" autoComplete="email" maxLength={200} required /></label><label>Password<input name="password" type="password" autoComplete={signup ? "new-password" : "current-password"} minLength={12} maxLength={200} required /><small>At least 12 characters. Email verification and password recovery are not available in this event build.</small></label><button className="button primary" disabled={busy}>{busy ? <LoaderCircle size={16} className="spin" /> : <ArrowRight size={16} />}{signup ? "Create trial account" : "Sign in"}</button><button type="button" className="text-button" onClick={() => { setSignup(!signup); setError(""); }}>{signup ? "Already have an account? Sign in" : "New to AgentPass? Create an account"}</button></form>;
  if (loading) return <main className="saas-loading"><Fingerprint size={38} /><p>Opening AgentPass…</p></main>;
  return <div className="saas">
    {!account ? <>
      <header className="saas-site-header"><a className="brand" href="/"><span className="brand-mark"><Fingerprint size={25} /></span>agentpass<span className="brand-period">.</span></a><nav><a href="#how-it-works">How it works</a><a href="#plugin">The plugin</a><button className="button secondary" onClick={() => { setSignup(false); setAuthOpen(true); }}>Sign in</button></nav></header>
      <main className="saas-landing">
        <div className="saas-hero"><section><div className="eyebrow">IDENTITY & SPENDING AUTHORITY FOR AI AGENTS</div><h1>Your agents.<br />Your accounts.<br /><em>Your rules.</em></h1><p>Give every agent an identity. Bind it to your payment accounts. Set the rules once, and keep control as your agents work.</p><div className="saas-hero-actions"><button className="button primary" onClick={() => { setSignup(true); setAuthOpen(true); }}>Create your workspace <ArrowRight size={17} /></button><a href="#how-it-works">See how it works ↓</a></div><small>Subscription SaaS · Free event trial · No merchant account needed to start</small></section>
          <div className="identity-stack" aria-label="Illustration of an agent identity and spending policy"><div className="identity-stack-heading"><Fingerprint size={24} /><span>ONE IDENTITY. EVERY CONNECTION.</span></div><div className="identity-example"><span className="identity-avatar">A</span><div><small>YOUR AGENT</small><h2>Atlas</h2><p>Owned by you · Connected through a plugin</p></div><ShieldCheck size={23} /></div><div className="identity-binding"><span>Payment account</span><strong>Your UPI or card account</strong><small>Connection and execution capability shown separately</small></div><div className="identity-binding"><span>Spending policy</span><strong>Merchant · Amount · Authority</strong><small>Checked outside the language model</small></div><div className="identity-stack-footer"><Link2 size={15} />Change the account. Keep the identity and history.</div><small className="illustration-label">Product illustration · not a funded account</small></div>
        </div>
        <section className="saas-explainer" id="how-it-works"><div><span className="eyebrow">THE CONTROL LAYER</span><h2>One place to manage<br />what your agents can do.</h2></div><ol><li><strong>Register an identity</strong><p>Give each agent its own credential and an owner-attested passport.</p></li><li><strong>Bind an account and set rules</strong><p>Choose the payment account, merchant allowlist and spending limits.</p></li><li><strong>Authorize exact purchases</strong><p>The plugin requests permission for a specific merchant, item and total.</p></li><li><strong>Keep the evidence</strong><p>Review requests, track reported orders and revoke new spending authority.</p></li></ol></section>
        <section className="saas-plugin-pitch" id="plugin"><Terminal size={27} /><div><h2>A plugin for the agent you already use.</h2><p>Connect Hermes or an MCP-compatible runtime. AgentPass supplies identity and authorization; your agent's browser or commerce tools handle shopping.</p><p className="saas-capability">This build supports account references and policy authorization. Autonomous UPI/card execution and paid subscriptions are not connected yet. No simulated balance is presented as a wallet.</p></div><button className="button secondary" onClick={() => { setSignup(true); setAuthOpen(true); }}>Connect an agent <ArrowUpRight size={16} /></button></section>
      </main><footer className="saas-site-footer"><span>AgentPass · BuildX</span><a href="https://github.com/Arkane-o7/BuildX-Buildonomics" target="_blank" rel="noreferrer">Source & setup ↗</a><a href="/lab">Earlier checkout experiment</a></footer>
    </> : <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark"><Fingerprint size={25} /></span>agentpass<span className="brand-period">.</span></a><div className="workspace"><span className="workspace-icon">{account.name.slice(0, 1).toUpperCase()}</span><div><strong>{account.name}</strong><small>Personal workspace</small></div></div><span className="nav-caption">MANAGE</span><nav>{tabs.map(({ name, icon: Icon }) => <button key={name} className={`nav-item ${tab === name ? "active" : ""}`} onClick={() => setTab(name)}><Icon size={18} />{name}</button>)}</nav><div className="sidebar-bottom"><div className="side-note"><ShieldCheck size={20} /><strong>Authority stays with you.</strong><p>Agent credentials cannot edit owner policies or connect payment accounts.</p></div><button className="nav-item" onClick={() => action(async () => { await api("logout", {}); setAccount(null); setToken(""); })}><LogOut size={16} />Sign out</button></div></aside>
      <div className="main-shell"><header className="topbar"><div className="breadcrumbs">Your workspace <ArrowRight size={12} /><strong>{tab}</strong></div><span className="mode-chip">Event trial · no subscription charge</span></header><main className="dashboard">
        <div className="page-heading"><div><div className="eyebrow">AGENTPASS CONTROL PLANE</div><h1>{tab === "Agents" ? "Identity comes first." : tab}</h1><p>{tab === "Agents" ? "Your agents, their payment accounts, and the authority you give them." : tab === "Payment accounts" ? "Manage account bindings without handing financial secrets to your agents." : tab === "Activity" ? "Policy decisions and order reports. Evidence sources stay explicit." : tab === "Connect plugin" ? "Scoped access for Hermes and other MCP-compatible agents." : "Your AgentPass software plan is separate from your agents’ purchases."}</p></div>{tab === "Agents" && <button className="button primary" onClick={() => setModal("agent")}><Plus size={16} />Register agent</button>}{tab === "Payment accounts" && <button className="button primary" onClick={() => setModal("wallet")}><Plus size={16} />Add account reference</button>}</div>
        {error && <div role="alert" className="alert error">{error}</div>}{notice && <div role="status" className="alert success">{notice}</div>}
        {tab === "Agents" && <>
          {!account.agents.length ? <section className="saas-empty"><Fingerprint size={40} /><h2>Meet your first agent.</h2><p>Register Hermes, give it an identity, and choose the rules that follow it.</p><button className="button primary" onClick={() => setModal("agent")}>Register your first agent <ArrowRight size={16} /></button></section> : <>
            <div className="fleet-grid">{account.agents.map(a => <button className={`fleet-card ${agent?.id === a.id ? "selected" : ""}`} key={a.id} onClick={() => setSelected(a.id)}><div className="fleet-top"><span className="identity-avatar">{a.name.slice(0, 1)}</span><span className={`status ${a.status}`}>{a.status === "active" ? "Active" : "Revoked"}</span></div><h2>{a.name}</h2><p>{a.runtime} · Owner attested</p><small className="mono">{a.id.slice(0, 18)}…</small><footer><span>{money(a.budget - a.spent - a.reserved)} allowance left</span><ArrowUpRight size={15} /></footer></button>)}</div>
            {agent && <div className="saas-agent-grid"><section className="panel"><div className="section-heading"><div><h2>{agent.name}'s spending policy</h2><p>Limits are permissions, not a funded balance.</p></div><SlidersHorizontal size={20} /></div><form key={agent.id + ':' + agent.policyVersion} className="saas-form padded" onSubmit={e => formAction(e, `agents/${agent.id}/policy`, f => ({ budget: Math.round(Number(f.get("budget")) * 100), perPurchase: Math.round(Number(f.get("cap")) * 100), allowedMerchants: String(f.get("merchants")).split(/[,\n]/).map(s => s.trim()).filter(Boolean) }))}><div className="form-row"><label>Total allowance (₹)<input name="budget" type="number" min="1" max="100000" step="0.01" defaultValue={agent.budget / 100} required /></label><label>Per purchase (₹)<input name="cap" type="number" min="1" max="100000" step="0.01" defaultValue={agent.perPurchase / 100} required /></label></div><label>Allowed merchant domains<input name="merchants" defaultValue={agent.allowedMerchants.join(", ")} placeholder="amazon.in, flipkart.com" required /><small>Comma-separated domains. Subdomains are included.</small></label><div className="saas-metrics"><span>Reported spend<strong>{money(agent.spent)}</strong></span><span>Reserved<strong>{money(agent.reserved)}</strong></span></div><button className="button primary" disabled={busy}>Save policy <Check size={16} /></button></form></section>
              <section className="panel"><div className="section-heading"><div><h2>Identity & account binding</h2><p>Switch accounts without resetting history.</p></div><Link2 size={20} /></div><div className="padded"><dl className="receipt-details"><dt>Stable identity</dt><dd className="mono">{agent.id}</dd><dt>Binding version</dt><dd>v{agent.bindingVersion}</dd><dt>Owner</dt><dd>{account.name}</dd><dt>Last plugin contact</dt><dd>{agent.lastSeen ? new Date(agent.lastSeen).toLocaleString() : "Not connected"}</dd></dl><form key={agent.id + ':' + agent.bindingVersion} className="saas-form" onSubmit={e => formAction(e, `agents/${agent.id}/binding`)}><label>Payment account<select name="walletId" defaultValue={agent.walletId || ""} required><option value="" disabled>Select an account reference</option>{account.wallets.map(w => <option key={w.id} value={w.id}>{w.label} · {w.maskedReference}</option>)}</select></label><button className="button secondary" disabled={busy || !account.wallets.length}>Save binding</button></form>{!account.wallets.length && <button className="text-button" onClick={() => { setTab("Payment accounts"); setModal("wallet"); }}>Add your first account reference →</button>}<p className="saas-capability">Payment execution: not connected. References identify the selected account; they do not grant access to funds.</p><button className={`button ${agent.status === "active" ? "danger-outline" : "secondary"}`} disabled={busy} onClick={() => action(async () => { await api(`agents/${agent.id}/${agent.status === "active" ? "revoke" : "resume"}`, {}); await refresh(); })}>{agent.status === "active" ? "Revoke spending authority" : "Restore spending authority"}</button></div></section>
            </div>}
          </>}
        </>}
        {tab === "Payment accounts" && <><div className="saas-capability prominent"><ShieldCheck size={18} /><div><strong>Your existing accounts, under your control.</strong><p>These are owner-declared, masked account references. A supported payment-provider connection is still needed for automatic debits. AgentPass does not hold money or verify your bank balance.</p></div></div>{!account.wallets.length ? <section className="saas-empty"><Wallet size={40} /><h2>No payment accounts yet.</h2><p>Add a UPI or card reference, then bind it to an agent.</p><button className="button primary" onClick={() => setModal("wallet")}>Add account reference</button></section> : <div className="fleet-grid">{account.wallets.map(w => <article className="fleet-card" key={w.id}><div className="fleet-top"><Wallet size={24} /><span className="status">Reference only</span></div><h2>{w.label}</h2><p>{w.kind.toUpperCase()} · {w.maskedReference}</p><footer><span>{account.agents.filter(a => a.walletId === w.id).length} agents bound</span><span>No execution adapter</span></footer></article>)}</div>}</>}
        {tab === "Activity" && <div className="saas-agent-grid"><section className="panel"><div className="section-heading"><div><h2>Purchase intents</h2><p>Authorizations are not payment confirmations.</p></div></div>{!account.intents.length ? <div className="empty-state"><ShieldCheck size={26} /><strong>No purchase requests yet</strong><p>Connect the plugin and ask your agent to authorize an external purchase.</p></div> : <div className="table-wrap"><table><thead><tr><th>Purchase / merchant</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{account.intents.map(i => <tr key={i.id}><td><strong>{i.item}</strong><small>{i.merchant}</small></td><td>{money(i.amount)}</td><td><span className={`status ${i.status === "blocked" ? "blocked" : i.status === "authorized" ? "awaiting_checkout" : ""}`}>{i.status === "reported" ? "Order reported" : i.status}</span></td><td><button className="icon-button" aria-label={`Inspect ${i.item}`} onClick={() => { setIntent(i); setVerification(""); setModal("intent"); }}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div>}</section><section className="panel"><div className="section-heading"><h2>Audit trail</h2><span className="polling">5s refresh</span></div><div className="timeline">{account.events.slice(0, 30).map(e => <article key={e.id}><div className={`timeline-icon ${e.type}`}><Activity size={13} /></div><div><div className="event-meta"><strong>{e.type}</strong><time>{new Date(e.time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div><p>{e.detail}</p></div></article>)}</div></section></div>}
        {tab === "Connect plugin" && <section className="panel plugin-setup"><div className="section-heading"><div><h2>Give your agent its passport.</h2><p>One credential per agent. Owner controls stay outside the runtime.</p></div><Terminal size={25} /></div><div className="padded"><ol className="setup-list"><li><strong>Register an agent and bind its payment account</strong><span>Configure the merchant allowlist and spending limits under Agents.</span></li><li><strong>Get a scoped plugin credential</strong><span>Credentials are shown once when an agent is registered. Rotate a credential to invalidate the previous one.</span></li><li><strong>Connect Hermes or another MCP client</strong><code>npm run plugin:configure</code><span>Run from this repository. Paste your credential into the local prompt, not into a chat. Then run <code>npm run hermes:platform</code>.</span></li><li><strong>Use the agent’s own shopping tools</strong><blockquote>“Find a suitable umbrella on Amazon India under ₹800. Use AgentPass to check my identity and authorize the exact item and final total. Do not claim it is paid unless the merchant confirms it.”</blockquote><span>This plugin does not browse or pay by itself. The isolated event profile exposes the control tools only; add them to your normal shopping-capable runtime for browser tasks.</span></li></ol>{agent && <div className="plugin-credential"><label>Agent<select value={agent.id} onChange={e => setSelected(e.target.value)}>{account.agents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="button secondary" disabled={busy} onClick={() => action(async () => { const r = await api(`agents/${agent.id}/token`, {}); setToken(r.token); setModal("token"); await refresh(); })}><KeyRound size={16} />Rotate & show new credential</button></div>}<p className="saas-capability">Plugin tools: passport, authorize_purchase, purchase_history, verify_authority, report_order. There is no raw signing tool, funding tool or policy-editing tool available to the agent.</p></div></section>}
        {tab === "Subscription" && <section className="panel subscription-panel"><span className="eyebrow">AGENTPASS SOFTWARE SUBSCRIPTION</span><h2>Event trial</h2><p>Your workspace includes up to 10 agents, 20 payment-account references, spending policies, plugin credentials and authorization history.</p><div className="saas-metrics"><span>Plan status<strong>Trial</strong></span><span>Subscription charged<strong>₹0</strong></span></div><div className="saas-capability"><strong>Paid billing is not connected.</strong><p>No paid subscription has been started. Subscription checkout will pay AgentPass for the software; it will not fund an agent wallet or pay Amazon.</p></div></section>}
      </main></div></div>}
    {(authOpen || modal) && <div className="modal-backdrop" onClick={() => { close(); setAuthOpen(false); }}><section className="modal" role="dialog" aria-modal="true" aria-label={authOpen ? "Account access" : modal || "Dialog"} onClick={e => e.stopPropagation()}><button className="modal-close icon-button" aria-label="Close" onClick={() => { close(); setAuthOpen(false); }}><X size={20} /></button>
      {authOpen && <><span className="modal-symbol"><Fingerprint /></span><h2>{signup ? "Your agents start here." : "Welcome back."}</h2><p>{signup ? "Create your AgentPass event-trial workspace." : "Sign in to manage your identities and spending rules."}</p>{authForm}</>}
      {modal === "agent" && <><h2>Register an agent</h2><p>Create a stable identity and a scoped plugin credential.</p><form className="saas-form" onSubmit={e => formAction(e, "agents")}><label>Agent name<input name="name" placeholder="Atlas" maxLength={60} required /></label><label>Runtime<input name="runtime" defaultValue="Hermes" maxLength={60} required /></label><button className="button primary" disabled={busy}>Register agent</button></form></>}
      {modal === "wallet" && <><h2>Add a payment-account reference</h2><p>We store a masked reference only. This does not connect a bank or enable automatic payment.</p><form className="saas-form" onSubmit={e => formAction(e, "wallets")}><label>Account label<input name="label" placeholder="Personal UPI" maxLength={60} required /></label><label>Account type<select name="kind" value={walletKind} onChange={e => setWalletKind(e.target.value)}><option value="upi">UPI</option><option value="card">Card</option></select></label><label>{walletKind === "upi" ? "UPI ID" : "Last four card digits only"}<input key={walletKind} name="reference" placeholder={walletKind === "upi" ? "name@bank" : "1234"} maxLength={walletKind === "upi" ? 100 : 4} pattern={walletKind === "card" ? "[0-9]{4}" : undefined} required autoComplete="off" /><small>Never enter a UPI PIN, complete card number, CVV or OTP.</small></label><button className="button primary" disabled={busy}>Save masked reference</button></form></>}
      {modal === "token" && <><span className="modal-symbol"><KeyRound /></span><h2>Your agent credential</h2><p>Shown once. Store it in your local plugin configuration. Do not put it in prompts or share it with other users.</p><textarea className="token-display" aria-label="Agent credential" readOnly value={token} /><button className="button primary" onClick={() => action(async () => { await navigator.clipboard.writeText(token); setNotice("Credential copied. Paste it into the local plugin setup prompt."); })}><Copy size={16} />Copy credential</button><p className="fine-print">Access is restricted to this account and agent. Rotate the credential to invalidate it.</p></>}
      {modal === "intent" && intent && <><h2>{intent.item}</h2><p>{intent.reason}</p><dl className="receipt-details"><dt>Merchant</dt><dd>{intent.merchant}</dd><dt>Total</dt><dd>{money(intent.amount)}</dd><dt>Status</dt><dd>{intent.status}</dd><dt>Payment evidence</dt><dd>{intent.evidenceSource || "No payment confirmed"}</dd><dt>Authorization expiry</dt><dd>{new Date(intent.expiresAt).toLocaleString()}</dd><dt>Request ID</dt><dd className="mono">{intent.requestId}</dd></dl>{intent.proof && <button className="button primary" disabled={busy} onClick={() => action(async () => { const r = await api("verify", { payload: intent.proof!.payload, signature: intent.proof!.signature }); setVerification(`${r.authorized ? "Current authority valid" : "Not currently authorized"}. ${r.reason}`); })}><ShieldCheck size={16} />Verify current authority</button>}{verification && <div className="alert" role="status">{verification}</div>}{intent.status === "authorized" && <button className="button secondary" disabled={busy} onClick={() => action(async () => { await api("cancel", { intentId: intent.id, confirmNoPayment: true }); setModal(null); await refresh(); })}>Confirm no payment occurred & release reservation</button>}<p className="fine-print">Releasing an AgentPass reservation does not cancel an order or payment at the merchant.</p></>}
      {error && <div role="alert" className="alert error">{error}</div>}{notice && <p role="status" className="fine-print">{notice}</p>}
    </section></div>}
  </div>;
}
